[package]
name = "sudoku_solver"
version = "0.1.0"
authors = ["kaaboaye <kaaboaye@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = '0.20'
